### ISSUE TITLE
Support removal of active mission instances.

### ISSUE THREAD

**Issue by StefanGsi** [molr/molr#47] opened 2020-02-07 08:21 UTC
We need an API to cleanup active mission instances.

Seems to be similar to #34

**Comment by kaifox** [comment] 2020-02-18 08:22
I would consider this as duplicate of #34. Therefore, I will close the other one.

Just to note: We were thinking some time ago that probably it would make sense to implement some persistence mechanism first, before adressing this on. (See #25 )

**Comment by StefanGsi** [comment] 2020-03-24 15:43
I have committed a first iteration/approach to remove mission instance from moles. Please check out the dispose-mission branches in molr and molr-gui-fx.

**Closed** 2020-04-23 17:50 UTC
